//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetGeneradorDB.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Linea", Namespace="http://Localhost/")]
    [System.SerializableAttribute()]
    public partial class Linea : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreLineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoLineaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreLinea {
            get {
                return this.NombreLineaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreLineaField, value) != true)) {
                    this.NombreLineaField = value;
                    this.RaisePropertyChanged("NombreLinea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodigoLinea {
            get {
                return this.CodigoLineaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoLineaField, value) != true)) {
                    this.CodigoLineaField = value;
                    this.RaisePropertyChanged("CodigoLinea");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imei", Namespace="http://Localhost/")]
    [System.SerializableAttribute()]
    public partial class Imei : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroIMEIField;
        
        private int Empresa_IdField;
        
        private System.DateTime FechaInicioField;
        
        private System.DateTime FechaFinField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreEmpresaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NumeroIMEI {
            get {
                return this.NumeroIMEIField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroIMEIField, value) != true)) {
                    this.NumeroIMEIField = value;
                    this.RaisePropertyChanged("NumeroIMEI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Empresa_Id {
            get {
                return this.Empresa_IdField;
            }
            set {
                if ((this.Empresa_IdField.Equals(value) != true)) {
                    this.Empresa_IdField = value;
                    this.RaisePropertyChanged("Empresa_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string rif {
            get {
                return this.rifField;
            }
            set {
                if ((object.ReferenceEquals(this.rifField, value) != true)) {
                    this.rifField = value;
                    this.RaisePropertyChanged("rif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string nombreEmpresa {
            get {
                return this.nombreEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreEmpresaField, value) != true)) {
                    this.nombreEmpresaField = value;
                    this.RaisePropertyChanged("nombreEmpresa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://Localhost/")]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RifField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Rif {
            get {
                return this.RifField;
            }
            set {
                if ((object.ReferenceEquals(this.RifField, value) != true)) {
                    this.RifField = value;
                    this.RaisePropertyChanged("Rif");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tabla", Namespace="http://Localhost/")]
    [System.SerializableAttribute()]
    public partial class Tabla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaParametro", Namespace="http://Localhost/")]
    [System.SerializableAttribute()]
    public partial class EmpresaParametro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ControlVersion", Namespace="http://Localhost/")]
    [System.SerializableAttribute()]
    public partial class ControlVersion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        private System.DateTime FechaPublicacionField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoField;
        
        private int CodigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime FechaPublicacion {
            get {
                return this.FechaPublicacionField;
            }
            set {
                if ((this.FechaPublicacionField.Equals(value) != true)) {
                    this.FechaPublicacionField = value;
                    this.RaisePropertyChanged("FechaPublicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Archivo {
            get {
                return this.ArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoField, value) != true)) {
                    this.ArchivoField = value;
                    this.RaisePropertyChanged("Archivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://Localhost/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Localhost/", ConfigurationName="ServiceReference1.WSCallCenterSoap")]
    public interface WSCallCenterSoap {
        
        // CODEGEN: Generating message contract since element name LineasResult from namespace http://Localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/Lineas", ReplyAction="*")]
        MedinetGeneradorDB.ServiceReference1.LineasResponse Lineas(MedinetGeneradorDB.ServiceReference1.LineasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/Lineas", ReplyAction="*")]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.LineasResponse> LineasAsync(MedinetGeneradorDB.ServiceReference1.LineasRequest request);
        
        // CODEGEN: Generating message contract since element name ImeisResult from namespace http://Localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/Imeis", ReplyAction="*")]
        MedinetGeneradorDB.ServiceReference1.ImeisResponse Imeis(MedinetGeneradorDB.ServiceReference1.ImeisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/Imeis", ReplyAction="*")]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.ImeisResponse> ImeisAsync(MedinetGeneradorDB.ServiceReference1.ImeisRequest request);
        
        // CODEGEN: Generating message contract since element name ImeisActivosResult from namespace http://Localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/ImeisActivos", ReplyAction="*")]
        MedinetGeneradorDB.ServiceReference1.ImeisActivosResponse ImeisActivos(MedinetGeneradorDB.ServiceReference1.ImeisActivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/ImeisActivos", ReplyAction="*")]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.ImeisActivosResponse> ImeisActivosAsync(MedinetGeneradorDB.ServiceReference1.ImeisActivosRequest request);
        
        // CODEGEN: Generating message contract since element name EmpresasResult from namespace http://Localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/Empresas", ReplyAction="*")]
        MedinetGeneradorDB.ServiceReference1.EmpresasResponse Empresas(MedinetGeneradorDB.ServiceReference1.EmpresasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/Empresas", ReplyAction="*")]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.EmpresasResponse> EmpresasAsync(MedinetGeneradorDB.ServiceReference1.EmpresasRequest request);
        
        // CODEGEN: Generating message contract since element name TablasDescargarResult from namespace http://Localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/TablasDescargar", ReplyAction="*")]
        MedinetGeneradorDB.ServiceReference1.TablasDescargarResponse TablasDescargar(MedinetGeneradorDB.ServiceReference1.TablasDescargarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/TablasDescargar", ReplyAction="*")]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.TablasDescargarResponse> TablasDescargarAsync(MedinetGeneradorDB.ServiceReference1.TablasDescargarRequest request);
        
        // CODEGEN: Generating message contract since element name TablasIncluirResult from namespace http://Localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/TablasIncluir", ReplyAction="*")]
        MedinetGeneradorDB.ServiceReference1.TablasIncluirResponse TablasIncluir(MedinetGeneradorDB.ServiceReference1.TablasIncluirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/TablasIncluir", ReplyAction="*")]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.TablasIncluirResponse> TablasIncluirAsync(MedinetGeneradorDB.ServiceReference1.TablasIncluirRequest request);
        
        // CODEGEN: Generating message contract since element name imei from namespace http://Localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/BuscarImei", ReplyAction="*")]
        MedinetGeneradorDB.ServiceReference1.BuscarImeiResponse BuscarImei(MedinetGeneradorDB.ServiceReference1.BuscarImeiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/BuscarImei", ReplyAction="*")]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.BuscarImeiResponse> BuscarImeiAsync(MedinetGeneradorDB.ServiceReference1.BuscarImeiRequest request);
        
        // CODEGEN: Generating message contract since element name ParametrosResult from namespace http://Localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/Parametros", ReplyAction="*")]
        MedinetGeneradorDB.ServiceReference1.ParametrosResponse Parametros(MedinetGeneradorDB.ServiceReference1.ParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/Parametros", ReplyAction="*")]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.ParametrosResponse> ParametrosAsync(MedinetGeneradorDB.ServiceReference1.ParametrosRequest request);
        
        // CODEGEN: Generating message contract since element name VersionesResult from namespace http://Localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/Versiones", ReplyAction="*")]
        MedinetGeneradorDB.ServiceReference1.VersionesResponse Versiones(MedinetGeneradorDB.ServiceReference1.VersionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/Versiones", ReplyAction="*")]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.VersionesResponse> VersionesAsync(MedinetGeneradorDB.ServiceReference1.VersionesRequest request);
        
        // CODEGEN: Generating message contract since element name imei from namespace http://Localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/registrarEquipo", ReplyAction="*")]
        MedinetGeneradorDB.ServiceReference1.registrarEquipoResponse registrarEquipo(MedinetGeneradorDB.ServiceReference1.registrarEquipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/registrarEquipo", ReplyAction="*")]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.registrarEquipoResponse> registrarEquipoAsync(MedinetGeneradorDB.ServiceReference1.registrarEquipoRequest request);
        
        // CODEGEN: Generating message contract since element name fDesde from namespace http://Localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/ImeisFacturador", ReplyAction="*")]
        MedinetGeneradorDB.ServiceReference1.ImeisFacturadorResponse ImeisFacturador(MedinetGeneradorDB.ServiceReference1.ImeisFacturadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/ImeisFacturador", ReplyAction="*")]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.ImeisFacturadorResponse> ImeisFacturadorAsync(MedinetGeneradorDB.ServiceReference1.ImeisFacturadorRequest request);
        
        // CODEGEN: Generating message contract since element name rifEmpresa from namespace http://Localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/enviarSMS", ReplyAction="*")]
        MedinetGeneradorDB.ServiceReference1.enviarSMSResponse enviarSMS(MedinetGeneradorDB.ServiceReference1.enviarSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/enviarSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.enviarSMSResponse> enviarSMSAsync(MedinetGeneradorDB.ServiceReference1.enviarSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/registrarImeis", ReplyAction="*")]
        void registrarImeis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/registrarImeis", ReplyAction="*")]
        System.Threading.Tasks.Task registrarImeisAsync();
        
        // CODEGEN: Generating message contract since element name instrucciones from namespace http://Localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/setInstruccionesSql", ReplyAction="*")]
        MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlResponse setInstruccionesSql(MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Localhost/setInstruccionesSql", ReplyAction="*")]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlResponse> setInstruccionesSqlAsync(MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LineasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Lineas", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.LineasRequestBody Body;
        
        public LineasRequest() {
        }
        
        public LineasRequest(MedinetGeneradorDB.ServiceReference1.LineasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LineasRequestBody {
        
        public LineasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LineasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LineasResponse", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.LineasResponseBody Body;
        
        public LineasResponse() {
        }
        
        public LineasResponse(MedinetGeneradorDB.ServiceReference1.LineasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class LineasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MedinetGeneradorDB.ServiceReference1.Linea[] LineasResult;
        
        public LineasResponseBody() {
        }
        
        public LineasResponseBody(MedinetGeneradorDB.ServiceReference1.Linea[] LineasResult) {
            this.LineasResult = LineasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImeisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Imeis", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.ImeisRequestBody Body;
        
        public ImeisRequest() {
        }
        
        public ImeisRequest(MedinetGeneradorDB.ServiceReference1.ImeisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ImeisRequestBody {
        
        public ImeisRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImeisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImeisResponse", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.ImeisResponseBody Body;
        
        public ImeisResponse() {
        }
        
        public ImeisResponse(MedinetGeneradorDB.ServiceReference1.ImeisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class ImeisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MedinetGeneradorDB.ServiceReference1.Imei[] ImeisResult;
        
        public ImeisResponseBody() {
        }
        
        public ImeisResponseBody(MedinetGeneradorDB.ServiceReference1.Imei[] ImeisResult) {
            this.ImeisResult = ImeisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImeisActivosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImeisActivos", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.ImeisActivosRequestBody Body;
        
        public ImeisActivosRequest() {
        }
        
        public ImeisActivosRequest(MedinetGeneradorDB.ServiceReference1.ImeisActivosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ImeisActivosRequestBody {
        
        public ImeisActivosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImeisActivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImeisActivosResponse", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.ImeisActivosResponseBody Body;
        
        public ImeisActivosResponse() {
        }
        
        public ImeisActivosResponse(MedinetGeneradorDB.ServiceReference1.ImeisActivosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class ImeisActivosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MedinetGeneradorDB.ServiceReference1.Imei[] ImeisActivosResult;
        
        public ImeisActivosResponseBody() {
        }
        
        public ImeisActivosResponseBody(MedinetGeneradorDB.ServiceReference1.Imei[] ImeisActivosResult) {
            this.ImeisActivosResult = ImeisActivosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmpresasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Empresas", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.EmpresasRequestBody Body;
        
        public EmpresasRequest() {
        }
        
        public EmpresasRequest(MedinetGeneradorDB.ServiceReference1.EmpresasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EmpresasRequestBody {
        
        public EmpresasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmpresasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmpresasResponse", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.EmpresasResponseBody Body;
        
        public EmpresasResponse() {
        }
        
        public EmpresasResponse(MedinetGeneradorDB.ServiceReference1.EmpresasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class EmpresasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MedinetGeneradorDB.ServiceReference1.Empresa[] EmpresasResult;
        
        public EmpresasResponseBody() {
        }
        
        public EmpresasResponseBody(MedinetGeneradorDB.ServiceReference1.Empresa[] EmpresasResult) {
            this.EmpresasResult = EmpresasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TablasDescargarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TablasDescargar", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.TablasDescargarRequestBody Body;
        
        public TablasDescargarRequest() {
        }
        
        public TablasDescargarRequest(MedinetGeneradorDB.ServiceReference1.TablasDescargarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TablasDescargarRequestBody {
        
        public TablasDescargarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TablasDescargarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TablasDescargarResponse", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.TablasDescargarResponseBody Body;
        
        public TablasDescargarResponse() {
        }
        
        public TablasDescargarResponse(MedinetGeneradorDB.ServiceReference1.TablasDescargarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class TablasDescargarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MedinetGeneradorDB.ServiceReference1.Tabla[] TablasDescargarResult;
        
        public TablasDescargarResponseBody() {
        }
        
        public TablasDescargarResponseBody(MedinetGeneradorDB.ServiceReference1.Tabla[] TablasDescargarResult) {
            this.TablasDescargarResult = TablasDescargarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TablasIncluirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TablasIncluir", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.TablasIncluirRequestBody Body;
        
        public TablasIncluirRequest() {
        }
        
        public TablasIncluirRequest(MedinetGeneradorDB.ServiceReference1.TablasIncluirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TablasIncluirRequestBody {
        
        public TablasIncluirRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TablasIncluirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TablasIncluirResponse", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.TablasIncluirResponseBody Body;
        
        public TablasIncluirResponse() {
        }
        
        public TablasIncluirResponse(MedinetGeneradorDB.ServiceReference1.TablasIncluirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class TablasIncluirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MedinetGeneradorDB.ServiceReference1.Tabla[] TablasIncluirResult;
        
        public TablasIncluirResponseBody() {
        }
        
        public TablasIncluirResponseBody(MedinetGeneradorDB.ServiceReference1.Tabla[] TablasIncluirResult) {
            this.TablasIncluirResult = TablasIncluirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarImeiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarImei", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.BuscarImeiRequestBody Body;
        
        public BuscarImeiRequest() {
        }
        
        public BuscarImeiRequest(MedinetGeneradorDB.ServiceReference1.BuscarImeiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class BuscarImeiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string imei;
        
        public BuscarImeiRequestBody() {
        }
        
        public BuscarImeiRequestBody(string imei) {
            this.imei = imei;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarImeiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarImeiResponse", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.BuscarImeiResponseBody Body;
        
        public BuscarImeiResponse() {
        }
        
        public BuscarImeiResponse(MedinetGeneradorDB.ServiceReference1.BuscarImeiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class BuscarImeiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MedinetGeneradorDB.ServiceReference1.Imei[] BuscarImeiResult;
        
        public BuscarImeiResponseBody() {
        }
        
        public BuscarImeiResponseBody(MedinetGeneradorDB.ServiceReference1.Imei[] BuscarImeiResult) {
            this.BuscarImeiResult = BuscarImeiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParametrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Parametros", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.ParametrosRequestBody Body;
        
        public ParametrosRequest() {
        }
        
        public ParametrosRequest(MedinetGeneradorDB.ServiceReference1.ParametrosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class ParametrosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int empre;
        
        public ParametrosRequestBody() {
        }
        
        public ParametrosRequestBody(int empre) {
            this.empre = empre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParametrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParametrosResponse", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.ParametrosResponseBody Body;
        
        public ParametrosResponse() {
        }
        
        public ParametrosResponse(MedinetGeneradorDB.ServiceReference1.ParametrosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class ParametrosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MedinetGeneradorDB.ServiceReference1.EmpresaParametro[] ParametrosResult;
        
        public ParametrosResponseBody() {
        }
        
        public ParametrosResponseBody(MedinetGeneradorDB.ServiceReference1.EmpresaParametro[] ParametrosResult) {
            this.ParametrosResult = ParametrosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VersionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Versiones", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.VersionesRequestBody Body;
        
        public VersionesRequest() {
        }
        
        public VersionesRequest(MedinetGeneradorDB.ServiceReference1.VersionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class VersionesRequestBody {
        
        public VersionesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VersionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VersionesResponse", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.VersionesResponseBody Body;
        
        public VersionesResponse() {
        }
        
        public VersionesResponse(MedinetGeneradorDB.ServiceReference1.VersionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class VersionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MedinetGeneradorDB.ServiceReference1.ControlVersion[] VersionesResult;
        
        public VersionesResponseBody() {
        }
        
        public VersionesResponseBody(MedinetGeneradorDB.ServiceReference1.ControlVersion[] VersionesResult) {
            this.VersionesResult = VersionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarEquipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarEquipo", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.registrarEquipoRequestBody Body;
        
        public registrarEquipoRequest() {
        }
        
        public registrarEquipoRequest(MedinetGeneradorDB.ServiceReference1.registrarEquipoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class registrarEquipoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string imei;
        
        public registrarEquipoRequestBody() {
        }
        
        public registrarEquipoRequestBody(string imei) {
            this.imei = imei;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarEquipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarEquipoResponse", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.registrarEquipoResponseBody Body;
        
        public registrarEquipoResponse() {
        }
        
        public registrarEquipoResponse(MedinetGeneradorDB.ServiceReference1.registrarEquipoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class registrarEquipoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool registrarEquipoResult;
        
        public registrarEquipoResponseBody() {
        }
        
        public registrarEquipoResponseBody(bool registrarEquipoResult) {
            this.registrarEquipoResult = registrarEquipoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImeisFacturadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImeisFacturador", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.ImeisFacturadorRequestBody Body;
        
        public ImeisFacturadorRequest() {
        }
        
        public ImeisFacturadorRequest(MedinetGeneradorDB.ServiceReference1.ImeisFacturadorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class ImeisFacturadorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fDesde;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fHasta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idEmpresa;
        
        public ImeisFacturadorRequestBody() {
        }
        
        public ImeisFacturadorRequestBody(string fDesde, string fHasta, int idEmpresa) {
            this.fDesde = fDesde;
            this.fHasta = fHasta;
            this.idEmpresa = idEmpresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImeisFacturadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImeisFacturadorResponse", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.ImeisFacturadorResponseBody Body;
        
        public ImeisFacturadorResponse() {
        }
        
        public ImeisFacturadorResponse(MedinetGeneradorDB.ServiceReference1.ImeisFacturadorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class ImeisFacturadorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MedinetGeneradorDB.ServiceReference1.ArrayOfString ImeisFacturadorResult;
        
        public ImeisFacturadorResponseBody() {
        }
        
        public ImeisFacturadorResponseBody(MedinetGeneradorDB.ServiceReference1.ArrayOfString ImeisFacturadorResult) {
            this.ImeisFacturadorResult = ImeisFacturadorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enviarSMS", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.enviarSMSRequestBody Body;
        
        public enviarSMSRequest() {
        }
        
        public enviarSMSRequest(MedinetGeneradorDB.ServiceReference1.enviarSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class enviarSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rifEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long idMensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string texto;
        
        public enviarSMSRequestBody() {
        }
        
        public enviarSMSRequestBody(string rifEmpresa, long idMensaje, string telefono, string texto) {
            this.rifEmpresa = rifEmpresa;
            this.idMensaje = idMensaje;
            this.telefono = telefono;
            this.texto = texto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enviarSMSResponse", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.enviarSMSResponseBody Body;
        
        public enviarSMSResponse() {
        }
        
        public enviarSMSResponse(MedinetGeneradorDB.ServiceReference1.enviarSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class enviarSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool enviarSMSResult;
        
        public enviarSMSResponseBody() {
        }
        
        public enviarSMSResponseBody(bool enviarSMSResult) {
            this.enviarSMSResult = enviarSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setInstruccionesSqlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setInstruccionesSql", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlRequestBody Body;
        
        public setInstruccionesSqlRequest() {
        }
        
        public setInstruccionesSqlRequest(MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class setInstruccionesSqlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string instrucciones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string registrationIds;
        
        public setInstruccionesSqlRequestBody() {
        }
        
        public setInstruccionesSqlRequestBody(string instrucciones, string registrationIds) {
            this.instrucciones = instrucciones;
            this.registrationIds = registrationIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setInstruccionesSqlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setInstruccionesSqlResponse", Namespace="http://Localhost/", Order=0)]
        public MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlResponseBody Body;
        
        public setInstruccionesSqlResponse() {
        }
        
        public setInstruccionesSqlResponse(MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Localhost/")]
    public partial class setInstruccionesSqlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool setInstruccionesSqlResult;
        
        public setInstruccionesSqlResponseBody() {
        }
        
        public setInstruccionesSqlResponseBody(bool setInstruccionesSqlResult) {
            this.setInstruccionesSqlResult = setInstruccionesSqlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCallCenterSoapChannel : MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCallCenterSoapClient : System.ServiceModel.ClientBase<MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap>, MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap {
        
        public WSCallCenterSoapClient() {
        }
        
        public WSCallCenterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCallCenterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCallCenterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCallCenterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MedinetGeneradorDB.ServiceReference1.LineasResponse MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.Lineas(MedinetGeneradorDB.ServiceReference1.LineasRequest request) {
            return base.Channel.Lineas(request);
        }
        
        public MedinetGeneradorDB.ServiceReference1.Linea[] Lineas() {
            MedinetGeneradorDB.ServiceReference1.LineasRequest inValue = new MedinetGeneradorDB.ServiceReference1.LineasRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.LineasRequestBody();
            MedinetGeneradorDB.ServiceReference1.LineasResponse retVal = ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).Lineas(inValue);
            return retVal.Body.LineasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.LineasResponse> MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.LineasAsync(MedinetGeneradorDB.ServiceReference1.LineasRequest request) {
            return base.Channel.LineasAsync(request);
        }
        
        public System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.LineasResponse> LineasAsync() {
            MedinetGeneradorDB.ServiceReference1.LineasRequest inValue = new MedinetGeneradorDB.ServiceReference1.LineasRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.LineasRequestBody();
            return ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).LineasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MedinetGeneradorDB.ServiceReference1.ImeisResponse MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.Imeis(MedinetGeneradorDB.ServiceReference1.ImeisRequest request) {
            return base.Channel.Imeis(request);
        }
        
        public MedinetGeneradorDB.ServiceReference1.Imei[] Imeis() {
            MedinetGeneradorDB.ServiceReference1.ImeisRequest inValue = new MedinetGeneradorDB.ServiceReference1.ImeisRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.ImeisRequestBody();
            MedinetGeneradorDB.ServiceReference1.ImeisResponse retVal = ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).Imeis(inValue);
            return retVal.Body.ImeisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.ImeisResponse> MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.ImeisAsync(MedinetGeneradorDB.ServiceReference1.ImeisRequest request) {
            return base.Channel.ImeisAsync(request);
        }
        
        public System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.ImeisResponse> ImeisAsync() {
            MedinetGeneradorDB.ServiceReference1.ImeisRequest inValue = new MedinetGeneradorDB.ServiceReference1.ImeisRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.ImeisRequestBody();
            return ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).ImeisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MedinetGeneradorDB.ServiceReference1.ImeisActivosResponse MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.ImeisActivos(MedinetGeneradorDB.ServiceReference1.ImeisActivosRequest request) {
            return base.Channel.ImeisActivos(request);
        }
        
        public MedinetGeneradorDB.ServiceReference1.Imei[] ImeisActivos() {
            MedinetGeneradorDB.ServiceReference1.ImeisActivosRequest inValue = new MedinetGeneradorDB.ServiceReference1.ImeisActivosRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.ImeisActivosRequestBody();
            MedinetGeneradorDB.ServiceReference1.ImeisActivosResponse retVal = ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).ImeisActivos(inValue);
            return retVal.Body.ImeisActivosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.ImeisActivosResponse> MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.ImeisActivosAsync(MedinetGeneradorDB.ServiceReference1.ImeisActivosRequest request) {
            return base.Channel.ImeisActivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.ImeisActivosResponse> ImeisActivosAsync() {
            MedinetGeneradorDB.ServiceReference1.ImeisActivosRequest inValue = new MedinetGeneradorDB.ServiceReference1.ImeisActivosRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.ImeisActivosRequestBody();
            return ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).ImeisActivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MedinetGeneradorDB.ServiceReference1.EmpresasResponse MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.Empresas(MedinetGeneradorDB.ServiceReference1.EmpresasRequest request) {
            return base.Channel.Empresas(request);
        }
        
        public MedinetGeneradorDB.ServiceReference1.Empresa[] Empresas() {
            MedinetGeneradorDB.ServiceReference1.EmpresasRequest inValue = new MedinetGeneradorDB.ServiceReference1.EmpresasRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.EmpresasRequestBody();
            MedinetGeneradorDB.ServiceReference1.EmpresasResponse retVal = ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).Empresas(inValue);
            return retVal.Body.EmpresasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.EmpresasResponse> MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.EmpresasAsync(MedinetGeneradorDB.ServiceReference1.EmpresasRequest request) {
            return base.Channel.EmpresasAsync(request);
        }
        
        public System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.EmpresasResponse> EmpresasAsync() {
            MedinetGeneradorDB.ServiceReference1.EmpresasRequest inValue = new MedinetGeneradorDB.ServiceReference1.EmpresasRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.EmpresasRequestBody();
            return ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).EmpresasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MedinetGeneradorDB.ServiceReference1.TablasDescargarResponse MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.TablasDescargar(MedinetGeneradorDB.ServiceReference1.TablasDescargarRequest request) {
            return base.Channel.TablasDescargar(request);
        }
        
        public MedinetGeneradorDB.ServiceReference1.Tabla[] TablasDescargar() {
            MedinetGeneradorDB.ServiceReference1.TablasDescargarRequest inValue = new MedinetGeneradorDB.ServiceReference1.TablasDescargarRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.TablasDescargarRequestBody();
            MedinetGeneradorDB.ServiceReference1.TablasDescargarResponse retVal = ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).TablasDescargar(inValue);
            return retVal.Body.TablasDescargarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.TablasDescargarResponse> MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.TablasDescargarAsync(MedinetGeneradorDB.ServiceReference1.TablasDescargarRequest request) {
            return base.Channel.TablasDescargarAsync(request);
        }
        
        public System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.TablasDescargarResponse> TablasDescargarAsync() {
            MedinetGeneradorDB.ServiceReference1.TablasDescargarRequest inValue = new MedinetGeneradorDB.ServiceReference1.TablasDescargarRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.TablasDescargarRequestBody();
            return ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).TablasDescargarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MedinetGeneradorDB.ServiceReference1.TablasIncluirResponse MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.TablasIncluir(MedinetGeneradorDB.ServiceReference1.TablasIncluirRequest request) {
            return base.Channel.TablasIncluir(request);
        }
        
        public MedinetGeneradorDB.ServiceReference1.Tabla[] TablasIncluir() {
            MedinetGeneradorDB.ServiceReference1.TablasIncluirRequest inValue = new MedinetGeneradorDB.ServiceReference1.TablasIncluirRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.TablasIncluirRequestBody();
            MedinetGeneradorDB.ServiceReference1.TablasIncluirResponse retVal = ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).TablasIncluir(inValue);
            return retVal.Body.TablasIncluirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.TablasIncluirResponse> MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.TablasIncluirAsync(MedinetGeneradorDB.ServiceReference1.TablasIncluirRequest request) {
            return base.Channel.TablasIncluirAsync(request);
        }
        
        public System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.TablasIncluirResponse> TablasIncluirAsync() {
            MedinetGeneradorDB.ServiceReference1.TablasIncluirRequest inValue = new MedinetGeneradorDB.ServiceReference1.TablasIncluirRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.TablasIncluirRequestBody();
            return ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).TablasIncluirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MedinetGeneradorDB.ServiceReference1.BuscarImeiResponse MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.BuscarImei(MedinetGeneradorDB.ServiceReference1.BuscarImeiRequest request) {
            return base.Channel.BuscarImei(request);
        }
        
        public MedinetGeneradorDB.ServiceReference1.Imei[] BuscarImei(string imei) {
            MedinetGeneradorDB.ServiceReference1.BuscarImeiRequest inValue = new MedinetGeneradorDB.ServiceReference1.BuscarImeiRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.BuscarImeiRequestBody();
            inValue.Body.imei = imei;
            MedinetGeneradorDB.ServiceReference1.BuscarImeiResponse retVal = ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).BuscarImei(inValue);
            return retVal.Body.BuscarImeiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.BuscarImeiResponse> MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.BuscarImeiAsync(MedinetGeneradorDB.ServiceReference1.BuscarImeiRequest request) {
            return base.Channel.BuscarImeiAsync(request);
        }
        
        public System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.BuscarImeiResponse> BuscarImeiAsync(string imei) {
            MedinetGeneradorDB.ServiceReference1.BuscarImeiRequest inValue = new MedinetGeneradorDB.ServiceReference1.BuscarImeiRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.BuscarImeiRequestBody();
            inValue.Body.imei = imei;
            return ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).BuscarImeiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MedinetGeneradorDB.ServiceReference1.ParametrosResponse MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.Parametros(MedinetGeneradorDB.ServiceReference1.ParametrosRequest request) {
            return base.Channel.Parametros(request);
        }
        
        public MedinetGeneradorDB.ServiceReference1.EmpresaParametro[] Parametros(int empre) {
            MedinetGeneradorDB.ServiceReference1.ParametrosRequest inValue = new MedinetGeneradorDB.ServiceReference1.ParametrosRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.ParametrosRequestBody();
            inValue.Body.empre = empre;
            MedinetGeneradorDB.ServiceReference1.ParametrosResponse retVal = ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).Parametros(inValue);
            return retVal.Body.ParametrosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.ParametrosResponse> MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.ParametrosAsync(MedinetGeneradorDB.ServiceReference1.ParametrosRequest request) {
            return base.Channel.ParametrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.ParametrosResponse> ParametrosAsync(int empre) {
            MedinetGeneradorDB.ServiceReference1.ParametrosRequest inValue = new MedinetGeneradorDB.ServiceReference1.ParametrosRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.ParametrosRequestBody();
            inValue.Body.empre = empre;
            return ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).ParametrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MedinetGeneradorDB.ServiceReference1.VersionesResponse MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.Versiones(MedinetGeneradorDB.ServiceReference1.VersionesRequest request) {
            return base.Channel.Versiones(request);
        }
        
        public MedinetGeneradorDB.ServiceReference1.ControlVersion[] Versiones() {
            MedinetGeneradorDB.ServiceReference1.VersionesRequest inValue = new MedinetGeneradorDB.ServiceReference1.VersionesRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.VersionesRequestBody();
            MedinetGeneradorDB.ServiceReference1.VersionesResponse retVal = ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).Versiones(inValue);
            return retVal.Body.VersionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.VersionesResponse> MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.VersionesAsync(MedinetGeneradorDB.ServiceReference1.VersionesRequest request) {
            return base.Channel.VersionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.VersionesResponse> VersionesAsync() {
            MedinetGeneradorDB.ServiceReference1.VersionesRequest inValue = new MedinetGeneradorDB.ServiceReference1.VersionesRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.VersionesRequestBody();
            return ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).VersionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MedinetGeneradorDB.ServiceReference1.registrarEquipoResponse MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.registrarEquipo(MedinetGeneradorDB.ServiceReference1.registrarEquipoRequest request) {
            return base.Channel.registrarEquipo(request);
        }
        
        public bool registrarEquipo(string imei) {
            MedinetGeneradorDB.ServiceReference1.registrarEquipoRequest inValue = new MedinetGeneradorDB.ServiceReference1.registrarEquipoRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.registrarEquipoRequestBody();
            inValue.Body.imei = imei;
            MedinetGeneradorDB.ServiceReference1.registrarEquipoResponse retVal = ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).registrarEquipo(inValue);
            return retVal.Body.registrarEquipoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.registrarEquipoResponse> MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.registrarEquipoAsync(MedinetGeneradorDB.ServiceReference1.registrarEquipoRequest request) {
            return base.Channel.registrarEquipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.registrarEquipoResponse> registrarEquipoAsync(string imei) {
            MedinetGeneradorDB.ServiceReference1.registrarEquipoRequest inValue = new MedinetGeneradorDB.ServiceReference1.registrarEquipoRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.registrarEquipoRequestBody();
            inValue.Body.imei = imei;
            return ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).registrarEquipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MedinetGeneradorDB.ServiceReference1.ImeisFacturadorResponse MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.ImeisFacturador(MedinetGeneradorDB.ServiceReference1.ImeisFacturadorRequest request) {
            return base.Channel.ImeisFacturador(request);
        }
        
        public MedinetGeneradorDB.ServiceReference1.ArrayOfString ImeisFacturador(string fDesde, string fHasta, int idEmpresa) {
            MedinetGeneradorDB.ServiceReference1.ImeisFacturadorRequest inValue = new MedinetGeneradorDB.ServiceReference1.ImeisFacturadorRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.ImeisFacturadorRequestBody();
            inValue.Body.fDesde = fDesde;
            inValue.Body.fHasta = fHasta;
            inValue.Body.idEmpresa = idEmpresa;
            MedinetGeneradorDB.ServiceReference1.ImeisFacturadorResponse retVal = ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).ImeisFacturador(inValue);
            return retVal.Body.ImeisFacturadorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.ImeisFacturadorResponse> MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.ImeisFacturadorAsync(MedinetGeneradorDB.ServiceReference1.ImeisFacturadorRequest request) {
            return base.Channel.ImeisFacturadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.ImeisFacturadorResponse> ImeisFacturadorAsync(string fDesde, string fHasta, int idEmpresa) {
            MedinetGeneradorDB.ServiceReference1.ImeisFacturadorRequest inValue = new MedinetGeneradorDB.ServiceReference1.ImeisFacturadorRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.ImeisFacturadorRequestBody();
            inValue.Body.fDesde = fDesde;
            inValue.Body.fHasta = fHasta;
            inValue.Body.idEmpresa = idEmpresa;
            return ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).ImeisFacturadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MedinetGeneradorDB.ServiceReference1.enviarSMSResponse MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.enviarSMS(MedinetGeneradorDB.ServiceReference1.enviarSMSRequest request) {
            return base.Channel.enviarSMS(request);
        }
        
        public bool enviarSMS(string rifEmpresa, long idMensaje, string telefono, string texto) {
            MedinetGeneradorDB.ServiceReference1.enviarSMSRequest inValue = new MedinetGeneradorDB.ServiceReference1.enviarSMSRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.enviarSMSRequestBody();
            inValue.Body.rifEmpresa = rifEmpresa;
            inValue.Body.idMensaje = idMensaje;
            inValue.Body.telefono = telefono;
            inValue.Body.texto = texto;
            MedinetGeneradorDB.ServiceReference1.enviarSMSResponse retVal = ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).enviarSMS(inValue);
            return retVal.Body.enviarSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.enviarSMSResponse> MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.enviarSMSAsync(MedinetGeneradorDB.ServiceReference1.enviarSMSRequest request) {
            return base.Channel.enviarSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.enviarSMSResponse> enviarSMSAsync(string rifEmpresa, long idMensaje, string telefono, string texto) {
            MedinetGeneradorDB.ServiceReference1.enviarSMSRequest inValue = new MedinetGeneradorDB.ServiceReference1.enviarSMSRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.enviarSMSRequestBody();
            inValue.Body.rifEmpresa = rifEmpresa;
            inValue.Body.idMensaje = idMensaje;
            inValue.Body.telefono = telefono;
            inValue.Body.texto = texto;
            return ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).enviarSMSAsync(inValue);
        }
        
        public void registrarImeis() {
            base.Channel.registrarImeis();
        }
        
        public System.Threading.Tasks.Task registrarImeisAsync() {
            return base.Channel.registrarImeisAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlResponse MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.setInstruccionesSql(MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlRequest request) {
            return base.Channel.setInstruccionesSql(request);
        }
        
        public bool setInstruccionesSql(string instrucciones, string registrationIds) {
            MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlRequest inValue = new MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlRequestBody();
            inValue.Body.instrucciones = instrucciones;
            inValue.Body.registrationIds = registrationIds;
            MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlResponse retVal = ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).setInstruccionesSql(inValue);
            return retVal.Body.setInstruccionesSqlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlResponse> MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap.setInstruccionesSqlAsync(MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlRequest request) {
            return base.Channel.setInstruccionesSqlAsync(request);
        }
        
        public System.Threading.Tasks.Task<MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlResponse> setInstruccionesSqlAsync(string instrucciones, string registrationIds) {
            MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlRequest inValue = new MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlRequest();
            inValue.Body = new MedinetGeneradorDB.ServiceReference1.setInstruccionesSqlRequestBody();
            inValue.Body.instrucciones = instrucciones;
            inValue.Body.registrationIds = registrationIds;
            return ((MedinetGeneradorDB.ServiceReference1.WSCallCenterSoap)(this)).setInstruccionesSqlAsync(inValue);
        }
    }
}
